package:
    name:           hidev-config
    namespace:      hiqdev\hidev\config
    label:          HiDevConfig
    title:          HiQDev's config for HiDev
    type:           yii2-extension
    keywords:       hiqdev, hidev, config
    year:           2015
