package:
    name:           hidev-config
    namespace:      hiqdev\hidev\config
    label:          HiQDevConfig
    headline:       HiDev HiQDev config
    title:          HiQDev vendor configuration for hidev
    type:           yii2-extension
    keywords:       hiqdev, hidev, config
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin enables [HiQDev](https://github.com/hiqdev) vendor configuration for HiDev.

        Contains information about HiQDev:
        * general data: vendor name and company title
        * contact data: email, forum, github page
        * authors data: names, emails, github and home pages
        * default license: BSD-3-Clause

        See [src/config.yml](src/config.yml).

require:
    hiqdev/hidev-config-php:    "*"

include:
    - src/config.yml
