package:
    name:           hidev-config
    namespace:      hiqdev\hidev\config
    label:          HiQDevConfig
    headline:       DEPRECATED
    title:          Deprecated in favour of [hiqdev/hidev-hiqdev]
    type:           yii2-extension
    keywords:       hiqdev, hidev, config
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        Use [hiqdev/hidev-hiqdev](https://github.com/hidev-hiqdev) instead.

require:
    hiqdev/hidev-config-php:    "*"

include:
    - src/config.yml
