package:
    name:           hidev-config
    namespace:      hiqdev\hidev\config
    label:          HiQDevConfig
    title:          HiQDev vendor hidev config
    type:           yii2-extension
    keywords:       hiqdev, hidev, config
    year:           2015

require:
    hiqdev/hidev-config-php:    "*"

include:
    - src/config.yml
